
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package teoria_automatas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RELACIONALES = 11;
  public static final int PUNTO = 9;
  public static final int ARIT = 14;
  public static final int INT = 24;
  public static final int LOGICOS_B = 19;
  public static final int RETURN = 6;
  public static final int TRUE = 22;
  public static final int ID = 5;
  public static final int NUM = 8;
  public static final int BOOLEAN = 21;
  public static final int COMA = 17;
  public static final int ASIGNACION = 12;
  public static final int EOF = 0;
  public static final int INCREMENT = 13;
  public static final int BEGIN_METODOS = 18;
  public static final int FALSE = 23;
  public static final int error = 1;
  public static final int PAR_CL = 16;
  public static final int PAR_OP = 15;
  public static final int LOGICOS_U = 20;
  public static final int PUNTOCOMA = 7;
  public static final int FOR = 4;
  public static final int NULL = 10;
  public static final int VOID = 25;
  public static final int LL_CL = 3;
  public static final int LL_OP = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LL_OP",
  "LL_CL",
  "FOR",
  "ID",
  "RETURN",
  "PUNTOCOMA",
  "NUM",
  "PUNTO",
  "NULL",
  "RELACIONALES",
  "ASIGNACION",
  "INCREMENT",
  "ARIT",
  "PAR_OP",
  "PAR_CL",
  "COMA",
  "BEGIN_METODOS",
  "LOGICOS_B",
  "LOGICOS_U",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "INT",
  "VOID"
  };
}

