
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package teoria_automatas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RELACIONALES = 9;
  public static final int ARIT = 13;
  public static final int LOGICOS_B = 21;
  public static final int RETURN = 7;
  public static final int ID = 5;
  public static final int NUM = 17;
  public static final int COMA = 16;
  public static final int ASIGNACION = 10;
  public static final int TIPOS_METODOS = 19;
  public static final int EOF = 0;
  public static final int TIPOS_VAR = 6;
  public static final int BEGIN_METODOS = 18;
  public static final int INCREMENTO = 11;
  public static final int error = 1;
  public static final int PAR_CL = 15;
  public static final int PAR_OP = 14;
  public static final int LOGICOS_U = 22;
  public static final int BOOLEANOS = 20;
  public static final int PUNTOCOMA = 8;
  public static final int DECREMENTO = 12;
  public static final int FOR = 4;
  public static final int LL_CL = 3;
  public static final int LL_OP = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LL_OP",
  "LL_CL",
  "FOR",
  "ID",
  "TIPOS_VAR",
  "RETURN",
  "PUNTOCOMA",
  "RELACIONALES",
  "ASIGNACION",
  "INCREMENTO",
  "DECREMENTO",
  "ARIT",
  "PAR_OP",
  "PAR_CL",
  "COMA",
  "NUM",
  "BEGIN_METODOS",
  "TIPOS_METODOS",
  "BOOLEANOS",
  "LOGICOS_B",
  "LOGICOS_U"
  };
}

