
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 07 15:01:16 CEST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RELACIONALES = 13;
  public static final int AND = 24;
  public static final int MENOS = 21;
  public static final int PUNTO = 9;
  public static final int INT = 29;
  public static final int OR = 10;
  public static final int CABECERA_METODOS = 23;
  public static final int NOT = 25;
  public static final int MENOSIGUAL = 32;
  public static final int RETURN = 6;
  public static final int LL_C = 3;
  public static final int PAR_C = 17;
  public static final int LL_A = 2;
  public static final int TRUE = 27;
  public static final int PAR_A = 16;
  public static final int POR = 19;
  public static final int ID = 5;
  public static final int NUM = 8;
  public static final int MASIGUAL = 31;
  public static final int BOOLEAN = 26;
  public static final int COMA = 18;
  public static final int ASIGNACION = 14;
  public static final int DISTINTO = 11;
  public static final int EOF = 0;
  public static final int DIV = 20;
  public static final int FALSE = 28;
  public static final int INCREMENTO = 15;
  public static final int error = 1;
  public static final int PUNTOCOMA = 7;
  public static final int DECREMENTO = 12;
  public static final int FOR = 4;
  public static final int NULL = 33;
  public static final int VOID = 30;
  public static final int MAS = 22;
}

