
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package teoria_automatas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RELACIONALES = 13;
  public static final int MENOS = 21;
  public static final int PUNTO = 9;
  public static final int INT = 29;
  public static final int OR = 10;
  public static final int LOGICOS_B = 24;
  public static final int MENOSMENOS = 31;
  public static final int RETURN = 6;
  public static final int TRUE = 27;
  public static final int POR = 19;
  public static final int ID = 5;
  public static final int NUM = 8;
  public static final int BOOLEAN = 26;
  public static final int COMA = 18;
  public static final int ASIGNACION = 14;
  public static final int DISTINTO = 11;
  public static final int EOF = 0;
  public static final int DIV = 20;
  public static final int INCREMENT = 15;
  public static final int BEGIN_METODOS = 23;
  public static final int FALSE = 28;
  public static final int PAR_CL = 17;
  public static final int error = 1;
  public static final int DECREMENTAR = 12;
  public static final int PAR_OP = 16;
  public static final int LOGICOS_U = 25;
  public static final int PUNTOCOMA = 7;
  public static final int FOR = 4;
  public static final int VOID = 30;
  public static final int MAS = 22;
  public static final int LL_CL = 3;
  public static final int LL_OP = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LL_OP",
  "LL_CL",
  "FOR",
  "ID",
  "RETURN",
  "PUNTOCOMA",
  "NUM",
  "PUNTO",
  "OR",
  "DISTINTO",
  "DECREMENTAR",
  "RELACIONALES",
  "ASIGNACION",
  "INCREMENT",
  "PAR_OP",
  "PAR_CL",
  "COMA",
  "POR",
  "DIV",
  "MENOS",
  "MAS",
  "BEGIN_METODOS",
  "LOGICOS_B",
  "LOGICOS_U",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "INT",
  "VOID",
  "MENOSMENOS"
  };
}

